#!/bin/bash
#
# Task executer
# PARAMETERS
#  $1 => the task file to load
# [$2 => the task command to call]
# [$+ => task sub-command options]


SHELLTASK_ROOT="$( cd -P "`dirname "$0"`/.." && pwd )"
if [[ -z $SHELLTASK_DIRS ]]
then
	SHELLTASK_DIRS="$SHELLTASK_ROOT/tasks"
fi



function task_help() {
	require "cli.task.sh"
	require "analyse.task.sh"

	local cmd_list=$( analyse_extract_commands $TASK_FILE)
	echo "Available commands for this task:"
	echo "$cmd_list" | sed -E "s:(.*):	- ${boldon}${purplef}$TASK_NAME ${bluef}\1${reset}:g"
}

function task_man() {
	require "analyse.task.sh"
	analyse_task_doc $TASK_FILE | less -R
}



## Print the command function for the given task
# return 1 if the command does not exist.
#
function command_function() {
	local cmd_function="${TASK_NAME}_${CMD_NAME}"
	if type $cmd_function &> /dev/null
	then
		echo $cmd_function
		return
	fi

	cmd_function="task_${CMD_NAME}"
	if type $cmd_function &> /dev/null
	then
		echo $cmd_function
		return
	fi

	return 1
}

function dispatch() {
	source "$SHELLTASK_ROOT/shelltask_functions.sh"

	initializeANSI
	[[ -t 1 ]] || dropANSI
	[[ -t 2 ]] || dropANSI

	# All this vars are reachable by the task functions
	TASK_NAME=$( basename "$0" ".task.sh" )
	TASK_FILE=$( locate_taskfile ${TASK_NAME}.task.sh )
	CMD_NAME="$1"
	shift

	require "${TASK_NAME}.task.sh" || return 1

	if ! command_function &> /dev/null && [[ "$TASK_NAME" = "shelltask" ]]
	then
		TASK_NAME="$CMD_NAME"
		TASK_FILE=$( locate_taskfile ${TASK_NAME}.task.sh )
		CMD_NAME="$1"
		shift

		if ! require "${TASK_NAME}.task.sh" &> /dev/null
		then
			require "cli.task.sh"
			cli_failure ${TASK_NAME} "is neither a task nor a shelltask command"
			return 1
		fi
	fi

	if command_function &> /dev/null
	then
		local cmd_function=$( command_function )
		$cmd_function "$@"
	else
		require "cli.task.sh"
		cli_failure "This command does not exist:"
		echo "	- ${boldon}${purplef}$TASK_NAME ${redf}$CMD_NAME${reset}"
		task_help
	fi
}

dispatch "$@"
