#!/bin/bash
#
# Task executer
# PARAMETERS
#  $1 => the task file to load
# [$2 => the task command to call]
# [$+ => task sub-command options]


SHELLTASK_ROOT="$( cd -P "`dirname "$0"`/.." && pwd )"

# TODO: Ensure that SHELLTASK_DIRS includes $SHELLTASK_ROOT/tasks
[[ -z $SHELLTASK_DIRS ]] && SHELLTASK_DIRS="$SHELLTASK_ROOT/tasks"

# TODO: it would be great to remove this file
source "$SHELLTASK_ROOT/shelltask_functions.sh"

# Disable color in shell if the outputs are not tty
initializeANSI
[[ -t 1 ]] && [[ -t 2 ]] || dropANSI


# TODO: move these common commands in a separate task file

##
#
function task_help() {
	require "analyse.task.sh"

	local cmd_list=$( analyse_extract_commands $TASK_FILE)
	echo "Available commands for this task:"
	echo "$cmd_list" | sed -E "s:(.*):	- ${boldon}${purplef}$TASK_NAME ${bluef}\1${reset}:g"
}

##
#
function task_man() {
	require "analyse.task.sh"

	analyse_task_doc $TASK_FILE | less -R
}



## Print the command function for the given task
# return 1 if the command does not exist.
#
function command_function() {
	local cmd_function="${TASK_NAME}_${CMD_NAME}"
	if type $cmd_function &> /dev/null
	then
		echo $cmd_function
		return
	fi

	cmd_function="task_${CMD_NAME}"
	if type $cmd_function &> /dev/null
	then
		echo $cmd_function
		return
	fi

	return 1
}

function task_run() {
	# All this vars are reachable by the task functions
	TASK_NAME=$( basename "$1" ".task.sh" )
	TASK_FILE=$( locate_taskfile ${TASK_NAME}.task.sh )
	CMD_NAME="$2"
	shift 2

	require "${TASK_NAME}.task.sh" || return 1

	# TODO: remove this line and add it to task file whch require it
	require "cli.task.sh"

	if command_function &> /dev/null
	then
		local cmd_function=$( command_function )
		$cmd_function "$@"
	else
		require "cli.task.sh"
		cli_failure "This command does not exist:"
		echo "	- ${boldon}${purplef}$TASK_NAME ${redf}$CMD_NAME${reset}"
		task_help
	fi
}

task_run "$0" "$@"
